spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true

logging:
  level:
    com:
      search: DEBUG
    feign: DEBUG
    org.hibernate.type: trace
    org.springframework: DEBUG

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
     default:
       loggerLevel: full

api-key:
  kakao: 490e77254a20d923aa088f7c4b043338
  naver:
    client:
      id: nyo4zi0E4nUnlBJBBdMG
      secret: 0kGzfy1UJd

